### ISSUE TITLE
Requirement to pick an address doesn't function

### ISSUE THREAD

**Issue by flareofghast** [DmitryEfimenko/ngAutocomplete#2]
Chrome autofill puts in a partial address but autocomplete doesn't make the user enter/ select an address as I thought was supposed to be the case.

**Comment by DmitryEfimenko** [comment]
Would disabling the autofill be an option?

**Comment by flareofghast** [comment]
I'll test it, I don't expect anyone would be using autofill in this at all/often but thought it was worth mentioning.

**Comment by flareofghast** [comment]
upon not picking an address I just get an error in the console 

```
Uncaught ReferenceError: mono is not defined
```

**Comment by DmitryEfimenko** [comment]
I think that error is caused by your app, not the autocomplete directive. There are no variables called `mono` in there. Check the error stack if possible

**Comment by flareofghast** [comment]
Hang on, just checked your plunker. Is ng-messages required for this to function properly?

**Comment by DmitryEfimenko** [comment]
it requires a minimum of AngularJs 1.3 because [it uses its validation methods](https://github.com/DmitryEfimenko/ngAutocomplete/blob/master/ngAutocomplete.js#L173). Having the `ng-messages` isn't required. You just won't see validation messages without them.
